steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_FULL_NAME/$SHORT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_FULL_NAME/$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'slector', '--image', 'gcr.io/$PROJECT_ID/$REPO_FULL_NAME/$SHORT_SHA', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/$REPO_FULL_NAME/$SHORT_SHA